# What is NumPy?
NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.<br>
docs-https://numpy.org/doc/stable/user/whatisnumpy.html

# Lists v/s NumPy<br>
Numpy data structures perform better in:

Size - Numpy data structures take up less space<br>
Performance - they have a need for speed and are faster than lists<br>
Functionality - SciPy and NumPy have optimized functions such as linear algebra operations built in.<br>

## Some important points about Numpy arrays:<br>

We can create a N-dimensional array in python using numpy.array().<br>
Array are by default Homogeneous, which means data inside an array must be of the same Datatype. (Note you can also create a structured array in python).<br>
Element wise operation is possible.<br>
Numpy array has the various function, methods, and variables, to ease our task of matrix computation.<br>
Elements of an array are stored contiguously in memory. For example, all rows of a two dimensioned array must have the same number of columns. Or a three dimensioned array must have the same number of rows and columns on each card.<br>

# First install NumPy in your computer(windows) by:<br>
In your favrouite directory press shift and right click then press open powershell window here:<br>
Then in powershell window type: pip install numpy<br>
Thats it NumPy will install in your pc(make sure to connect your computer to internet first) <br>
Now lets import it in our jupyter notebook to work with:

In [1]:
import numpy as np

## Intializing array

In [2]:
arr = np.array([1,2,3])
print(arr)


[1 2 3]


In [3]:
# 2D array
arr2d = np.array([[1,2,4.23],[4,5.40,6]])
print(arr2d)

[[1.   2.   4.23]
 [4.   5.4  6.  ]]


In [76]:
# 3d array
C = np.array([[[1,2,3],[4,5,6],[0,0,-1]],[[-1,-2,-3],[-4,-5,-6],[0,0,1]]]) #  array of , two dimensional arrays is 3d array

In [77]:
C[1,0,2]

-3

In [78]:
C.ndim

3

In [79]:
type(C)


numpy.ndarray

In [80]:
C.shape # (how namy 2d array are there, how many 1d array are there in each, how many elements are there in each 1d array)

(2, 3, 3)

In [82]:
C.shape[0] # how many 2d array are there

2

In [4]:
# getting dimensions
arr2d.ndim

2

In [5]:
# getting shape
arr2d.shape

(2, 3)

In [6]:
# data type of array
print(arr.dtype)
print(arr2d.dtype)

int32
float64


In [7]:
# we can intialize size of our need
c = np.array([7,8,9], dtype='int32') 
d = np.array([5,6,7], dtype='int64') 

# getting type, itemsize, size
print(c.dtype)
print(d.dtype)

print(c.itemsize) # gives 4 bytes (1 byte = 8 bits)
print(d.itemsize) # gives 8 bytes

print(c.size) # 3 elements
print(d.size)

int32
int64
4
8
3
3


In [8]:
# total size of array
print(c.nbytes) # no of bytes ( size * itemsize)
print(arr2d.nbytes) # floats take larger size than int

12
48


# Analysing NumPy Arrays

In [9]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [10]:
a.shape

(2, 7)

In [11]:
# accessing a specific element 
a[1,5] # remember row and columns start from index zero  

13

In [12]:
# can specify negative indexes
a[0,-1]

7

In [13]:
# slicing /accessing row 
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [14]:
# accessing a column
a[:,2]

array([ 3, 10])

In [15]:
# accseeing by [startindex:endindex:stepsize]
a[0,1:6:2] # means row 0, start from 1 index to 6 index(excluding it), with stepsize of 2 

array([2, 4, 6])

In [16]:
# changeing elements 
a[1,6] = 15
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 15]])

In [17]:
# changing column
a[:,3] = [14,16] 
a

array([[ 1,  2,  3, 14,  5,  6,  7],
       [ 8,  9, 10, 16, 12, 13, 15]])

In [18]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [19]:
# how to access element:
b[0,1,1] # 0 means from first set, 1 means second row of set first, 1 means element at index 1 in that set and row

4

In [20]:
# replace
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [21]:
# replace 
b[:,1,:] = [[9,9],[8,8]]

In [22]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

# array kinds

In [23]:
# zero 0 matrix 
np.zeros(3)

array([0., 0., 0.])

In [24]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
np.zeros((2,3,3)) # 3d , The conceptual syntax for 3D array is this: data_type array_name[table][row][column]

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [26]:
# 4d
np.zeros((2,3,3,3)) # [table][no of set in each table] [rows] [column]

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]])

In [27]:
# All 1s matrix
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [28]:
#with datatypye
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [29]:
# Any other number
np.full((2,2), 55)

array([[55, 55],
       [55, 55]])

In [30]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.36776983, 0.49607772],
       [0.99029225, 0.76810202],
       [0.30602037, 0.11416978],
       [0.55699895, 0.97327717]])

In [31]:
# Any other number (full_like)
np.full_like(a, 4) # a is array that is already build so we can use its shape again for creating new array

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [32]:
# Random Integer values
np.random.randint(2,4, size=(3,3))

array([[3, 2, 2],
       [2, 3, 3],
       [2, 2, 2]])

In [33]:
np.random.randint(-4,8, size=(3,3)) # run again and again it gives different output everytime

array([[ 3, -3,  3],
       [ 7,  2, -2],
       [ 7,  7,  6]])

In [34]:
np.random.random_sample(a.shape)

array([[0.96576187, 0.47425959, 0.6214288 , 0.91260871, 0.53097481,
        0.92210867, 0.06666466],
       [0.5530476 , 0.01536134, 0.58899803, 0.48655964, 0.15664781,
        0.90199273, 0.35293721]])

In [35]:
# The identity matrix
np.identity(3) # only one parameter because itendity is square

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
# Repeat an array
ar = np.array([[1,2,3]])
r1 = np.repeat(ar,5, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [37]:
ar = np.array([[1,2,3]])
r1 = np.repeat(ar,3, axis=1)
print(r1)

[[1 1 1 2 2 2 3 3 3]]


# ques:

In [38]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z # or [1:4,1:4] = [row:column]= [row to row : column to column]
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## careful while copying

### use .copy() method otherwise it changes original array also

# Mathematics:

In [39]:
arry = np.array([1,5,2,6])
arry

array([1, 5, 2, 6])

In [40]:
arry + 2

array([3, 7, 4, 8])

In [41]:
arry - 2

array([-1,  3,  0,  4])

In [42]:
arry * 2

array([ 2, 10,  4, 12])

In [43]:
arry / 2

array([0.5, 2.5, 1. , 3. ])

In [44]:
arry += 2
print(arry)

[3 7 4 8]


In [45]:
arry2 = np.array([0,7,8,9])


In [46]:
arry + arry2

array([ 3, 14, 12, 17])

In [47]:
arry ** 3

array([ 27, 343,  64, 512], dtype=int32)

In [48]:
# taking sin, cos of vlues
np.sin(arry2)

array([0.        , 0.6569866 , 0.98935825, 0.41211849])

In [49]:
np.cos(arry2)

array([ 1.        ,  0.75390225, -0.14550003, -0.91113026])

# Linear algebra

In [50]:
aa = np.ones((2,3))
print(aa)

bb = np.full((3,2), 2)
print(bb)

np.matmul(aa,bb) # matrix multiplication 

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [51]:
# Find the determinant
cc = np.identity(3)
np.linalg.det(cc) 

1.0

In [52]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

# Statistics

In [53]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
np.min(stats)

1

In [55]:
np.min(stats, axis=1) # axis = 1 on row basis

array([1, 4])

In [56]:
np.min(stats, axis=0) # on column basis

array([1, 2, 3])

In [57]:
np.max(stats, axis=1)

array([3, 6])

In [58]:
np.max(stats, axis=0)

array([4, 5, 6])

In [59]:
np.sum(stats, axis=0) 

array([5, 7, 9])

# Reorganizing Arrays

In [60]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((8,1))
print(after)
after1 = before.reshape((4,2))
print(after1)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [61]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

k=np.vstack([v1,v2,v1,v2])
print(k)

# accessing elements
k[[0,1,2,3],[0,1,2,3]] # [[rows],[columns]]

[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]


array([1, 6, 3, 8])

In [62]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# exerscise

load data from file

In [63]:
filedata = np.genfromtxt('Numpydataex.txt', delimiter=',') # all number count should be equal
filedata


array([[  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
         11.,  12.,  13.,  14.,  15.,  16.],
       [ 10.,  11.,   1.,   2.,   1.,   3.,   1.,   6.,  16.,  25.,   2.,
          3.,   2.,   3.,  14.,   2.,   6.],
       [ 10.,  11.,   1.,   2.,   1.,   3.,   1.,   6.,  16.,  25.,   2.,
          3.,   2.,   3.,  14.,   2.,   6.],
       [101., 111.,  11.,  21.,  12., 332.,  13.,  63., 165., 255.,  25.,
         35.,  25.,  35., 154.,  52.,  66.]])

In [64]:
filedata = filedata.astype('int32') # specifying float to int you can write as your wish
print(filedata)

[[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16]
 [ 10  11   1   2   1   3   1   6  16  25   2   3   2   3  14   2   6]
 [ 10  11   1   2   1   3   1   6  16  25   2   3   2   3  14   2   6]
 [101 111  11  21  12 332  13  63 165 255  25  35  25  35 154  52  66]]


In [65]:
#accessing data : fancy way
filedata[[0,2,3],15:]

array([[15, 16],
       [ 2,  6],
       [52, 66]])

In [66]:
filedata[1:3,0:2] # right value in row and column gets excluded 

array([[10, 11],
       [10, 11]])

In [67]:
filedata[[0,1,2,3],[1,2,3,4]] # the no of arguments should be equal on both side, it fetches value in diagonal way 

array([ 1,  1,  2, 12])

# Boolean Masking and Advanced Indexing

In [68]:
np.any(filedata>50,axis=0) # any vlaue is greater than 50 column wise

array([ True,  True, False, False, False,  True, False,  True,  True,
        True, False, False, False, False,  True,  True,  True])

In [69]:
np.all(filedata>50,axis=0) # all values are grater than 50 in each colum, each value

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False])

In [70]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True, False,  True,
         True,  True,  True,  True,  True,  True, False, False]])

In [71]:
filedata > 50

array([[False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False],
       [ True,  True, False, False, False,  True, False,  True,  True,
         True, False, False, False, False,  True,  True,  True]])

In [72]:
filedata < 100

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True],
       [False, False,  True,  True,  True, False,  True,  True, False,
        False,  True,  True,  True,  True, False,  True,  True]])

In [73]:
((filedata > 50) & (filedata < 100))

array([[False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False,  True, False,
        False, False, False, False, False, False,  True,  True]])

In [74]:
((filedata > 50) | (filedata < 100))

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True]])

In [75]:
# index with a list in NumPy
m = np.array([1,2,3,4,5,6,7,8,9])
m[[1,2,8]]

array([2, 3, 9])